# Makefile generated by create_cocotb_makefile.py
# Do not edit this file manually.

SIM ?= verilator
TOPLEVEL_LANG ?= verilog
export TWO_MEMORIES = True
COMPILE_ARGS ?= --language 1800-2005 -DSIMULATION -Wno-fatal -Wno-lint
EXTRA_ARGS += --trace --trace-structs
VERILOG_INCLUDE_DIRS += /eda/processor_ci_verification/example/tinyriscv/rtl/core/
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/clint.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/csr_reg.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/ctrl.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/div.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/ex.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/id.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/id_ex.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/if_id.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/pc_reg.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/regs.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/rib.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/core/tinyriscv.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv/rtl/utils/gen_dff.v
VERILOG_SOURCES += /eda/processor_ci_verification/example/tinyriscv.sv
TOPLEVEL = processorci_top
MODULE = cocotb_labeler
include $(shell cocotb-config --makefiles)/Makefile.sim
